[alias]
wasm = "build --release --lib --target wasm32-unknown-unknown"
unit-test = "test --lib"
schema = "run --bin schema"

[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "link-arg=--stack-first",
  "-C", "link-arg=--export-table",
  "-C", "target-feature=-bulk-memory",
]
